return {
	"folke/snacks.nvim",
	lazy = false,
	priority = 1000,
	opts = {
		dashboard = require("plugins.snacks.dashboard"),
		picker = require("plugins.snacks.picker"),
		notifier = require("plugins.snacks.notifier"),
		terminal = require("plugins.snacks.terminal"),
		animate = { enabled = true },
		bigfile = { enabled = true },
		indent = { enabled = true },
		input = { enabled = true },
		bufdelete = { enabled = true },
		quickfile = { enabled = true },
		scope = { enabled = false },
		statuscolumn = { enabled = true },
		words = { enabled = true },
		image = require("plugins.snacks.image"),
		explorer = { enabled = false },
		scroll = require("plugins.snacks.scroll"),
		scratch = { enabled = true },
	},

	keys = require("plugins.snacks.keys"),
}
